server:
  port: 8082

spring:
  application:
    name: ADMIN-ADMINS
  cloud:
    nacos:
      server-addr: 106.15.43.178:8848


  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://106.15.43.178:3306/watermelon?characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
  redis:
    host: 106.15.43.178
    port: 6379

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.xsy.entity